-- ===== Fragen-Tabellen für Die Tafelrunde =====
-- In Supabase: SQL Editor → "New query" → alles hier einfügen → "Run".
-- Man kann das gefahrlos mehrmals ausführen: Vorhandene Tabellen und Fragen bleiben erhalten.
--
-- Eine Tabelle pro Spielart. Die Spalten heißen genau wie in Google Sheets,
-- damit der CSV-Import direkt passt.
-- Sicherheit: Jeder darf die Fragen LESEN. Ändern kann man sie nur im Supabase-Dashboard.

create table if not exists public.multiple_choice (
  id            bigint generated by default as identity primary key,
  kategorie     text,
  schwierigkeit text default 'casual',
  text          text,
  antwort1      text,
  antwort2      text,
  antwort3      text,
  antwort4      text,
  richtig       text,  -- Nummer der richtigen Antwort: 1, 2, 3 oder 4
  info          text
);

create table if not exists public.wahr_falsch (
  id            bigint generated by default as identity primary key,
  kategorie     text,
  schwierigkeit text default 'casual',
  text          text,
  richtig       text,  -- wahr oder falsch
  info          text
);

create table if not exists public.schaetzfrage (
  id            bigint generated by default as identity primary key,
  kategorie     text,
  schwierigkeit text default 'casual',
  text          text,
  antwort       text,  -- die richtige Zahl
  einheit       text,  -- z. B. km, Jahre (darf leer sein)
  info          text
);

create table if not exists public.reihenfolge (
  id            bigint generated by default as identity primary key,
  kategorie     text,
  schwierigkeit text default 'casual',
  text          text,
  antwort1      text,  -- antwort1 bis antwort6 in der RICHTIGEN Reihenfolge
  antwort2      text,
  antwort3      text,
  antwort4      text,
  antwort5      text,
  antwort6      text,
  info          text
);

create table if not exists public.kaertchen (
  id            bigint generated by default as identity primary key,
  kategorie     text,
  schwierigkeit text default 'casual',
  text          text,
  richtig       text,  -- mehrere, getrennt mit ; (Semikolon)
  falsch        text,  -- mehrere, getrennt mit ; (Semikolon)
  info          text
);

create table if not exists public.entweder_oder (
  id            bigint generated by default as identity primary key,
  kategorie     text,
  schwierigkeit text default 'casual',
  text          text,  -- darf leer sein ("option1 oder option2?")
  option1       text,
  option2       text,
  aussage1      text,
  zu1           text,  -- 1 oder 2: zu welcher Option die Aussage gehört
  aussage2      text,
  zu2           text,
  aussage3      text,
  zu3           text,
  aussage4      text,
  zu4           text,
  aussage5      text,
  zu5           text,
  info          text
);

-- Sicherheitsregeln (RLS): für alle Tabellen nur Lesen erlauben
do $$
declare
  t text;
begin
  foreach t in array array['multiple_choice', 'wahr_falsch', 'schaetzfrage',
                           'reihenfolge', 'kaertchen', 'entweder_oder']
  loop
    execute format('alter table public.%I enable row level security', t);
    execute format('drop policy if exists "Fragen lesen" on public.%I', t);
    execute format('create policy "Fragen lesen" on public.%I for select to anon, authenticated using (true)', t);
    execute format('grant select on public.%I to anon, authenticated', t);
  end loop;
end $$;
